import Foundation
import AppKit

@MainActor
public final class ClipboardManager: ObservableObject {
    @Published public private(set) var history: [ClipboardItem] = []
    @Published public var searchQuery: String = ""
    @Published public var isMonitoring: Bool = false

    /// Items larger than this are ignored (huge pastes bloat storage and slow the UI).
    public static let maxItemLength = 500_000

    /// Pasteboard markers used by password managers and other apps to flag content
    /// that must not be recorded (see nspasteboard.org).
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    /// Encryption + UserDefaults writes happen off the main thread, serialized here.
    private static let persistenceQueue = DispatchQueue(label: "com.promptera.clipboard.persistence", qos: .utility)

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var monitorTimer: Timer?
    private let maxHistoryItems: Int
    private let storageKey = "promptera_clipboard_history"
    private let encryptionService = EncryptionService.shared
    private let persistent: Bool

    /// - Parameter persistent: `false` gives an in-memory manager that neither reads
    ///   the pasteboard nor touches storage (used for demo/screenshot data).
    public init(maxHistoryItems: Int = 50, persistent: Bool = true) {
        self.maxHistoryItems = maxHistoryItems
        self.persistent = persistent
        self.lastChangeCount = pasteboard.changeCount
        guard persistent else { return }
        loadPersistedHistory()
        startMonitoring()

        // Check initial pasteboard content
        checkPasteboard()
    }

    deinit {
        monitorTimer?.invalidate()
    }

    public var filteredHistory: [ClipboardItem] {
        let query = searchQuery.trimmingCharacters(in: .whitespacesAndNewlines)
        if query.isEmpty {
            return history
        }
        return history.filter { $0.matches(query) }
    }

    public var latestItem: ClipboardItem? {
        history.first
    }

    public func startMonitoring() {
        guard !isMonitoring else { return }
        isMonitoring = true
        let timer = Timer(timeInterval: 0.75, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkPasteboard()
            }
        }
        // Tolerance lets macOS coalesce wake-ups, reducing idle energy use.
        timer.tolerance = 0.25
        RunLoop.main.add(timer, forMode: .common)
        monitorTimer = timer
    }

    public func stopMonitoring() {
        monitorTimer?.invalidate()
        monitorTimer = nil
        isMonitoring = false
    }

    public func checkPasteboard() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        if let types = pasteboard.types, types.contains(where: Self.ignoredTypes.contains) {
            return
        }

        guard let text = pasteboard.string(forType: .string),
              text.utf16.count <= Self.maxItemLength,
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }

        // Avoid duplicate consecutive entry
        if let first = history.first, first.content == text {
            return
        }

        insertAtTop(text)
    }

    public func copyToClipboard(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        insertAtTop(text)
    }

    /// Merges items into the history (e.g. from an import) without touching the
    /// system pasteboard. Existing content is kept; the newest items stay on top.
    public func mergeItems(_ items: [ClipboardItem]) {
        var seen = Set(history.map(\.content))
        let newItems = items.filter { seen.insert($0.content).inserted }
        guard !newItems.isEmpty else { return }
        let merged = (history + newItems).sorted { $0.timestamp > $1.timestamp }
        history = Array(merged.prefix(maxHistoryItems))
        persistHistory()
    }

    public func removeItem(id: UUID) {
        history.removeAll { $0.id == id }
        persistHistory()
    }

    public func clearHistory() {
        history.removeAll()
        persistHistory()
    }

    private func insertAtTop(_ text: String) {
        // If already in history somewhere, remove old occurrence and move to top
        var updated = history.filter { $0.content != text }
        updated.insert(ClipboardItem(content: text), at: 0)
        if updated.count > maxHistoryItems {
            updated.removeLast(updated.count - maxHistoryItems)
        }
        history = updated
        persistHistory()
    }

    private func persistHistory() {
        guard persistent else { return }
        let snapshot = history
        let key = storageKey
        let encryptionService = encryptionService
        Self.persistenceQueue.async {
            do {
                let data = try JSONEncoder().encode(snapshot)
                let encrypted = try encryptionService.encrypt(data)
                UserDefaults.standard.set(encrypted, forKey: key)
            } catch {
                // Non-critical persistence failure
            }
        }
    }

    private func loadPersistedHistory() {
        // Wait for any pending write so we never read stale data.
        Self.persistenceQueue.sync {}
        guard let encryptedData = UserDefaults.standard.data(forKey: storageKey) else { return }
        do {
            let data = try encryptionService.decrypt(encryptedData)
            let loaded = try JSONDecoder().decode([ClipboardItem].self, from: data)
            self.history = Array(loaded.prefix(maxHistoryItems))
        } catch {
            // If decryption fails (e.g., key rotated), clear history
            self.history = []
            UserDefaults.standard.removeObject(forKey: storageKey)
        }
    }
}
